[pytest]
# Добавляем маркеры
markers =
    positive: Позитивные тесты
    search: Тесты поиска
    regression: Регрессионные тесты

# Настройки отчетов
addopts =
    -v
    --strict-markers
    --tb=short
    --html=report.html
    --self-contained-html

# Папки с тестами
testpaths = tests

# Фильтры предупреждений
filterwarnings =
    ignore::DeprecationWarning